# Arguments:
static: 2
dynamic: 1
seed: 42

offset: 100
workspace: 10
time: 60

# Filename settings
csv: "default"
output: null        # i believe this is currently unsued

# which filters to use
filters:
    inclusive: true
    exclusive: true
    dynamic: true
    datmo: true
    # initiating with true values?
    intiating: true
    init:
        x0: ${vehicle_model.x0}
        P0:
            - 0.05
            - 0.05
            - 10.       # in degrees

# debugging settings
plot: false
debug: false

# Config settings
defaults:
    - motion_model: bodyframe
    - sensor: full
    - _self_

fp_list:
    - 1.

vehicle_model:
    type: Bicycle
    x0:
        - 0.
        - 0.
        - 10.   # in degrees
    v1: 0.2     # noise parameters
    v2: 5       # in degrees