# Hydra configs
hydra:
    job:
        name: testjob
    run:
        dir: ./.tmp/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    sweep:
        dir : ./results/${hydra.job.name}
        subdir : ${now:%Y-%m-%d_%H-%M-%S}


# Arguments:
static: 30
dynamic: 10
seed: 42

offset: 100
workspace: 10
time: 60
history: true

# Filename settings
csv: ${hydra.job.name}

# initiating with true values?
intiating: true

x0: ${vehicle_model.x0}
P0:
    - 0.05
    - 0.05
    - 10.       # in degrees

# debugging settings
plot: false
debug: false
verbose: false

# Config settings
defaults:
    - filter:
        # - inclusive
        # - false_positive
        - dynamic
        - datmo
        - exclusive
    - motion_model:
      - static
      - kinematic
      - bodyframe
    - sensor: full
    - _self_

fp_list:
    - 1.

vehicle_model:
    # _target_: roboticstoolbox.Bicycle -> not possible, because of v1 and v2 unknown keys
    # animation: car
    x0:
        - 0.
        - 0.
        - 10.   # in degrees
    v1: 0.2     # noise parameters
    v2: 5       # in degrees