# Hydra configs
hydra:
    job:
        name: ${static}_${dynamic}_${seed}
        id: ${now:%Y-%m-%d _%H-%M-%S}
    run:
        dir: ./.tmp/${experiment_name}/${hydra.job.name}
    sweep:
        dir : ./results/${experiment_name}                 
        subdir : ${hydra.job.name}
    callbacks: 
        save_job_info:
            _target_: hydra.experimental.callbacks.PickleJobInfoCallback

experiment_name: hydratest_${now:%Y%m%d} #_%H-%M-%S

# Arguments:
static: 2
dynamic: 1
seed: 42

offset: 100
workspace: 10
time: 60
history: true

# Filename settings
csv: ${experiment_name}

# initiating with true values?
intiating: true

x0: ${vehicle_model.x0}
P0:
    - 0.05
    - 0.05
    - 10.       # in degrees

# debugging settings
plot: false
debug: false
store_hist: true
verbose: false

# Config settings
defaults:
    - filter:
        # - inclusive
        # - false_positive
        - dynamic
        - datmo
        - exclusive
    - motion_model:
    #   - static
      - kinematic
    #   - bodyframe
    - sensor: full
    - _self_

fp_list:        # todo -change this for the FPs
    - 1.

vehicle_model:
    # _target_: roboticstoolbox.Bicycle -> not possible, because of v1 and v2 unknown keys
    # animation: car
    x0:
        - 0.
        - 0.
        - 10.   # in degrees
    v1: 0.2     # noise parameters
    v2: 5       # in degrees