# Hydra configs
hydra:
    mode: MULTIRUN
    job:
        name: ${static}_${dynamic}_${seed}
        id: ${now:%Y-%m-%d _%H-%M-%S}
    run:
        dir: ./${target_dir}/${experiment_name}/${hydra.job.name}
    sweep:
        dir : ./${target_dir}/${experiment_name}                 
        subdir : ${hydra.job.name}
    sweeper:
        params:
            seed: range(0,21)
            static: range(3,21)
            dynamic: range(1,6)
    callbacks: 
        save_job_info:
            _target_: hydra.experimental.callbacks.PickleJobInfoCallback

experiment_name: fptest_${now:%Y%m%d} #_%H-%M-%S

# Arguments:
static: 3
dynamic: 3
seed: 42

offset: 100
workspace: 10
time: 60
history: true

# Filename settings
target_dir: ".tmp"
csv: ${experiment_name}

# initiating with true values?
intiating: true

x0: ${vehicle_model.x0}
P0:
    - 0.05
    - 0.05
    - 10.       # in degrees

# debugging settings
debug: false
store_hist: false
verbose: false

# Config settings
#! todo - here we can set the indices that need to be filled in as ??? -> ignore idcs, dynamic idcs etc. then that'll get stored with cfg - hopefully
defaults:
    - filter:
        # - inclusive
        - false_positive
        # - dynamic
        # - datmo
        - exclusive
    - motion_model:
      - static
      - kinematic
      - bodyframe
    - sensor: full
    - _self_

vehicle_model:
    # _target_: roboticstoolbox.Bicycle -> not possible, because of v1 and v2 unknown keys
    # animation: car
    x0:
        - 0.
        - 0.
        - 10.   # in degrees
    v1: 0.2     # noise parameters
    v2: 5       # in degrees