# Noise parameters for a static model - passed as parameters to constructor
# ? can probably be called with class name here, right?
static:
    name: StaticModel
    # _target_: mrekf.motionmodels.StaticModel

    # noise
    V:
        - 0.2
        - 0.2